SELECT C.COMPANY_CODE, 
       C.FOUNDER,
       (SELECT COUNT(DISTINCT LEAD_MANAGER_CODE)
        FROM LEAD_MANAGER AS L
       WHERE C.COMPANY_CODE = L.COMPANY_CODE),
       (SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE)
        FROM SENIOR_MANAGER AS S
       WHERE C.COMPANY_CODE = S.COMPANY_CODE),
       (SELECT COUNT(DISTINCT MANAGER_CODE)
        FROM MANAGER AS M
       WHERE C.COMPANY_CODE = M.COMPANY_CODE),
       (SELECT COUNT(DISTINCT EMPLOYEE_CODE)
        FROM EMPLOYEE AS E
       WHERE C.COMPANY_CODE = E.COMPANY_CODE)
FROM COMPANY AS C
ORDER BY COMPANY_CODE ASC