SELECT *
FROM 
    (SELECT CITY,
            LENGTH(CITY)
    FROM STATION
    GROUP BY CITY
    ORDER BY LENGTH(CITY)
    LIMIT 1) AS S1
UNION ALL 
SELECT *
FROM 
    (SELECT CITY,
            LENGTH(CITY)
    FROM STATION
    GROUP BY CITY
    ORDER BY LENGTH(CITY) DESC
    LIMIT 1) AS S2